#contraseña 12345
INSERT INTO `forum_i`.`users` (`id`,`email`,`name`,`password`,`enabled`) VALUES (2, "mcuadrai@gmail.com", "Mario", "$2a$10$V6SOh6anao5ektEj8ib/cOZRp74u6Vz9S1Am5xwxRUKCMTOVhMUN.", TRUE);
INSERT INTO `forum_i`.`users` (`id`,`email`,`name`,`password`,`enabled`) VALUES (3, "carlos@gmail.com", "Carlos","$2a$10$XOmWLEiYMz9g2kCgnweCiu0UIeDGJ8WG1IaCG4CJ17/Cui5fRM4.K", TRUE);

INSERT INTO `forum_i`.`authorities` (userId, authority) VALUES(2, 'VERIFIED');
INSERT INTO `forum_i`.`authorities` (userId, authority) VALUES(3, 'VERIFIED');



INSERT INTO `forum_i`.`tipoevaluacion` (`nombre`, `sonTodosxor`) VALUES ('PNI method', TRUE);
INSERT INTO `forum_i`.`tipoevaluacion` (`nombre`, `sonTodosxor`) VALUES ('negative emotion', FALSE);
INSERT INTO `forum_i`.`tipoevaluacion` (`nombre`, `sonTodosxor`) VALUES ('bad politic', FALSE);
INSERT INTO `forum_i`.`tipoevaluacion` (`nombre`, `sonTodosxor`) VALUES ('attitude', FALSE);



INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('1', 'p', 'positivo', '1', '1'   , 'olymp-accordion-open-icon' );
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('2', 'n', 'negativo', '2', '1'   , 'olymp-accordion-close-icon');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('3', 'i', 'interesante', '3', '1', 'olymp-thunder-icon');

INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`) VALUES ('4', 'd', 'descortés', '1', '2');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`) VALUES ('5', 'd2', 'grosería', '2', '2');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`) VALUES ('6', 'd3', 'violencia', '3', '2');

INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`) VALUES ('13', 'c',  'colectivista', '1', '3');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`) VALUES ('14', 'l',  'libertario',   '2', '3');

INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('9', 'p', 'populista', '1', '4', 'olymp-circus-icon');
#INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('10', 'v', 'victima',  '3', '4', 'olymp-victim-icon');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('11', 't', 'troll',    '2', '4', 'olymp-troll-icon');
INSERT INTO `forum_i`.`choice` (`id`, `codigoNemotecnico`, `name`, `orderChoice`, `tipo_evaluacion_id`, `rutaIcono`) VALUES ('12', 'v', 'violento', '4', '4', 'olymp-violent-icon');



INSERT INTO `forum_i`.`cargo` (`nombre`) VALUES ('presidente');
INSERT INTO `forum_i`.`cargo` (`nombre`) VALUES ('senador');
INSERT INTO `forum_i`.`cargo` (`nombre`) VALUES ('diputado');
INSERT INTO `forum_i`.`cargo` (`nombre`) VALUES ('alcalde o relacionado');
INSERT INTO `forum_i`.`cargo` (`nombre`) VALUES ('otros');

INSERT INTO `forum_i`.`tipoidentificacion` (`nombre`) VALUES ('número único nacional');
INSERT INTO `forum_i`.`tipoidentificacion` (`nombre`) VALUES ('pasaporte');

INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('1', 'Presidencial');
INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('2', 'Parlamentaria/Asamblea');
INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('3', 'Senatorial');
INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('4', 'De Diputados');
INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('5', 'Alcaldía');
INSERT INTO `forum_i`.`tipoeleccion` (`id`, `nombre`) VALUES ('6', 'Otros');


INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('15','De Arica y Parinacota');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('01','De Tarapacá');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('02','De Antofagasta');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('03','De Atacama');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('04','De Coquimbo');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('05','De Valparaíso');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('06','Del Libertador B. O Higgins');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('07','Del Maule');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('08','Del Bíobío');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('09','De La Araucanía');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('14','De Los Ríos');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('10','De Los Lagos');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('11','De Aisén del Gral. C. Ibáñez del Campo');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('12','De Magallanes y de La Antártica Chilena');
INSERT INTO `forum_i`.`region` (`codigo`, `nombre`) VALUES ('13','Metropolitana de Santiago');


INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('15101','Arica','15');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('15102','Camarones','15');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('15201','Putre','15');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('15202','General Lagos','15');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01101','Iquique','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01402','Camiña','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01403','Colchane','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01404','Huara','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01405','Pica','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01401','Pozo Almonte','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('01107','Alto Hospicio','01');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02101','Antofagasta','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02102','Mejillones','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02103','Sierra Gorda','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02104','Taltal','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02201','Calama','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02202','Ollagüe','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02203','San Pedro de Atacama','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02301','Tocopilla','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('02302','María Elena','02');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03101','Copiapó','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03102','Caldera','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03103','Tierra Amarilla','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03201','Chañaral','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03202','Diego de Almagro','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03301','Vallenar','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03302','Alto del Carmen','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03303','Freirina','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('03304','Huasco','03');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04101','La Serena','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04102','Coquimbo','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04103','Andacollo','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04104','La Higuera','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04105','Paiguano','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04106','Vicuña','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04201','Illapel','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04202','Canela','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04203','Los Vilos','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04204','Salamanca','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04301','Ovalle','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04302','Combarbalá','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04303','Monte Patria','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04304','Punitaqui','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('04305','Río Hurtado','04');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05101','Valparaíso','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05102','Casablanca','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05103','Concón','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05104','Juan Fernández','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05105','Puchuncaví','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05801','Quilpué','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05107','Quintero','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05804','Villa Alemana','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05109','Viña del Mar','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05201','Isla  de Pascua','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05301','Los Andes','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05302','Calle Larga','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05303','Rinconada','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05304','San Esteban','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05401','La Ligua','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05402','Cabildo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05403','Papudo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05404','Petorca','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05405','Zapallar','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05501','Quillota','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05502','Calera','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05503','Hijuelas','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05504','La Cruz','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05802','Limache','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05506','Nogales','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05803','Olmué','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05601','San Antonio','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05602','Algarrobo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05603','Cartagena','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05604','El Quisco','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05605','El Tabo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05606','Santo Domingo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05701','San Felipe','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05702','Catemu','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05703','Llaillay','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05704','Panquehue','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05705','Putaendo','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('05706','Santa María','05');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06101','Rancagua','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06102','Codegua','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06103','Coinco','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06104','Coltauco','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06105','Doñihue','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06106','Graneros','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06107','Las Cabras','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06108','Machalí','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06109','Malloa','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06110','Mostazal','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06111','Olivar','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06112','Peumo','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06113','Pichidegua','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06114','Quinta de Tilcoco','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06115','Rengo','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06116','Requínoa','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06117','San Vicente','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06201','Pichilemu','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06202','La Estrella','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06203','Litueche','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06204','Marchihue','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06205','Navidad','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06206','Paredones','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06301','San Fernando','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06302','Chépica','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06303','Chimbarongo','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06304','Lolol','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06305','Nancagua','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06306','Palmilla','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06307','Peralillo','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06308','Placilla','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06309','Pumanque','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('06310','Santa Cruz','06');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07101','Talca','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07102','Constitución','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07103','Curepto','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07104','Empedrado','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07105','Maule','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07106','Pelarco','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07107','Pencahue','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07108','Río Claro','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07109','San Clemente','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07110','San Rafael','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07201','Cauquenes','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07202','Chanco','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07203','Pelluhue','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07301','Curicó','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07302','Hualañé','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07303','Licantén','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07304','Molina','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07305','Rauco','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07306','Romeral','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07307','Sagrada Familia','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07308','Teno','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07309','Vichuquén','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07401','Linares','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07402','Colbún','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07403','Longaví','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07404','Parral','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07405','Retiro','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07406','San Javier','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07407','Villa Alegre','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('07408','Yerbas Buenas','07');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08101','Concepción','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08102','Coronel','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08103','Chiguayante','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08104','Florida','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08105','Hualqui','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08106','Lota','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08107','Penco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08108','San Pedro de la Paz','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08109','Santa Juana','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08110','Talcahuano','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08111','Tomé','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08112','Hualpén','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08201','Lebu','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08202','Arauco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08203','Cañete','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08204','Contulmo','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08205','Curanilahue','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08206','Los Álamos','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08207','Tirúa','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08301','Los Ángeles','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08302','Antuco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08303','Cabrero','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08304','Laja','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08305','Mulchén','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08306','Nacimiento','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08307','Negrete','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08308','Quilaco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08309','Quilleco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08310','San Rosendo','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08311','Santa Bárbara','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08312','Tucapel','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08313','Yumbel','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08314','Alto Biobío','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08401','Chillán','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08402','Bulnes','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08403','Cobquecura','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08404','Coelemu','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08405','Coihueco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08406','Chillán Viejo','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08407','El Carmen','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08408','Ninhue','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08409','Ñiquén','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08410','Pemuco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08411','Pinto','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08412','Portezuelo','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08413','Quillón','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08414','Quirihue','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08415','Ránquil','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08416','San Carlos','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08417','San Fabián','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08418','San Ignacio','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08419','San Nicolás','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08420','Treguaco','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('08421','Yungay','08');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09101','Temuco','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09102','Carahue','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09103','Cunco','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09104','Curarrehue','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09105','Freire','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09106','Galvarino','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09107','Gorbea','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09108','Lautaro','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09109','Loncoche','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09110','Melipeuco','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09111','Nueva Imperial','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09112','Padre Las Casas','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09113','Perquenco','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09114','Pitrufquén','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09115','Pucón','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09116','Saavedra','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09117','Teodoro Schmidt','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09118','Toltén','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09119','Vilcún','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09120','Villarrica','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09121','Cholchol','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09201','Angol','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09202','Collipulli','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09203','Curacautín','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09204','Ercilla','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09205','Lonquimay','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09206','Los Sauces','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09207','Lumaco','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09208','Purén','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09209','Renaico','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09210','Traiguén','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('09211','Victoria','09');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14101','Valdivia','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14102','Corral','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14202','Futrono','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14201','La Unión','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14203','Lago Ranco','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14103','Lanco','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14104','Los Lagos','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14105','Máfil','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14106','Mariquina','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14107','Paillaco','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14108','Panguipulli','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('14204','Río Bueno','14');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10101','Puerto Montt','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10102','Calbuco','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10103','Cochamó','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10104','Fresia','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10105','Frutillar','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10106','Los Muermos','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10107','Llanquihue','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10108','Maullín','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10109','Puerto Varas','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10201','Castro','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10202','Ancud','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10203','Chonchi','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10204','Curaco de Vélez','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10205','Dalcahue','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10206','Puqueldón','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10207','Queilén','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10208','Quellón','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10209','Quemchi','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10210','Quinchao','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10301','Osorno','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10302','Puerto Octay','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10303','Purranque','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10304','Puyehue','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10305','Río Negro','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10306','San Juan de la Costa','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10307','San Pablo','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10401','Chaitén','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10402','Futaleufú','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10403','Hualaihué','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('10404','Palena','10');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11101','Coihaique','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11102','Lago Verde','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11201','Aisén','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11202','Cisnes','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11203','Guaitecas','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11301','Cochrane','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11302','Higgins','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11303','Tortel','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11401','Chile Chico','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('11402','Río Ibáñez','11');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12101','Punta Arenas','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12102','Laguna Blanca','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12103','Río Verde','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12104','San Gregorio','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12201','Cabo de Hornos','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12202','Antártica','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12301','Porvenir','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12302','Primavera','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12303','Timaukel','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12401','Natales','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('12402','Torres del Paine','12');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13101','Santiago','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13102','Cerrillos','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13103','Cerro Navia','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13104','Conchalí','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13105','El Bosque','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13106','Estación Central','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13107','Huechuraba','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13108','Independencia','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13109','La Cisterna','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13110','La Florida','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13111','La Granja','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13112','La Pintana','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13113','La Reina','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13114','Las Condes','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13115','Lo Barnechea','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13116','Lo Espejo','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13117','Lo Prado','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13118','Macul','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13119','Maipú','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13120','Ñuñoa','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13121','Pedro Aguirre Cerda','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13122','Peñalolén','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13123','Providencia','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13124','Pudahuel','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13125','Quilicura','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13126','Quinta Normal','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13127','Recoleta','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13128','Renca','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13129','San Joaquín','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13130','San Miguel','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13131','San Ramón','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13132','Vitacura','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13201','Puente Alto','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13202','Pirque','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13203','San José de Maipo','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13301','Colina','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13302','Lampa','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13303','Tiltil','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13401','San Bernardo','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13402','Buin','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13403','Calera de Tango','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13404','Paine','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13501','Melipilla','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13502','Alhué','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13503','Curacaví','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13504','María Pinto','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13505','San Pedro','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13601','Talagante','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13602','El Monte','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13603','Isla de Maipo','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13604','Padre Hurtado','13');
INSERT INTO `forum_i`.`comuna` (`codigo`, `nombre`, `region_codigo`) VALUES ('13605','Peñaflor','13');

#Falta un pais, ver http://www.electionguide.org/countries/
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TMP','East Timor','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PSE','Palestine','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ATA','Antarctica','Antarctica');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MNP','Northern Mariana Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PRI','Puerto Rico','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ATG','Antigua and Barbuda','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BHS','Bahamas','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BLZ','Belize','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BRB','Barbados','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DNK','Denmark','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ESP','Spain','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GBR','United Kingdom','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GRD','Grenada','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('JAM','Jamaica','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('JOR','Jordan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('JPN','Japan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KHM','Cambodia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KNA','Saint Kitts and Nevis','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LCA','Saint Lucia','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LIE','Liechtenstein','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LSO','Lesotho','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LUX','Luxembourg','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MAR','Morocco','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MCO','Monaco','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NLD','Netherlands','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NOR','Norway','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NPL','Nepal','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NZL','New Zealand','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PNG','Papua New Guinea','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SLB','Solomon Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SWE','Sweden','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('THA','Thailand','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TUV','Tuvalu','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VCT','Saint Vincent and the Grenadines','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KWT','Kuwait','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AUS','Australia','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BEL','Belgium','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CAN','Canada','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MYS','Malaysia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BVT','Bouvet Island','Antarctica');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SJM','Svalbard and Jan Mayen','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AIA','Anguilla','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BMU','Bermuda','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CYM','Cayman Islands','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FLK','Falkland Islands','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GIB','Gibraltar','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IOT','British Indian Ocean Territory','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MSR','Montserrat','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PCN','Pitcairn','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SGS','South Georgia and the South Sandwich Islands','Antarctica');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SHN','Saint Helena','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TCA','Turks and Caicos Islands','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VGB','Virgin Islands, British','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('UMI','United States Minor Outlying Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ARE','United Arab Emirates','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ARG','Argentina','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AUT','Austria','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AZE','Azerbaijan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BIH','Bosnia and Herzegovina','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BRA','Brazil','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DEU','Germany','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FSM','Micronesia, Federated States of','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IND','India','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MDG','Madagascar','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MEX','Mexico','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NGA','Nigeria','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('RUS','Russian Federation','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('USA','United States','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VEN','Venezuela','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('YUG','Yugoslavia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CHE','Switzerland','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VAT','Holy See (Vatican City State)','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AFG','Afghanistan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IRN','Iran','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SDN','Sudan','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BTN','Bhutan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('QAT','Qatar','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SAU','Saudi Arabia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SWZ','Swaziland','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TON','Tonga','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BHR','Bahrain','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BRN','Brunei','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('OMN','Oman','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ATF','French Southern territories','Antarctica');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NCL','New Caledonia','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PYF','French Polynesia','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('WLF','Wallis and Futuna','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('COK','Cook Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NIU','Niue','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TKL','Tokelau','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ABW','Aruba','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ANT','Netherlands Antilles','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ESH','Western Sahara','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GLP','Guadeloupe','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GUF','French Guiana','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MTQ','Martinique','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('REU','RÃ©union','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('WSM','Samoa','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AND','Andorra','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FRO','Faroe Islands','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GRL','Greenland','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CHN','China','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('AGO','Angola','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ALB','Albania','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ARM','Armenia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BDI','Burundi','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BEN','Benin','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BFA','Burkina Faso','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BGD','Bangladesh','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BGR','Bulgaria','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BLR','Belarus','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BOL','Bolivia','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('BWA','Botswana','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CAF','Central African Republic','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CHL','Chile','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CIV','CÃ´te dÂ’Ivoire','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CMR','Cameroon','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('COD','Congo, The Democratic Republic of the','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('COG','Congo','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('COL','Colombia','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('COM','Comoros','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CPV','Cape Verde','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CRI','Costa Rica','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CYP','Cyprus','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CZE','Czech Republic','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DJI','Djibouti','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DMA','Dominica','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DOM','Dominican Republic','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('DZA','Algeria','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ECU','Ecuador','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('EGY','Egypt','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ERI','Eritrea','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('EST','Estonia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ETH','Ethiopia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FIN','Finland','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FJI','Fiji Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('FRA','France','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GAB','Gabon','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GEO','Georgia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GHA','Ghana','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GIN','Guinea','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GMB','Gambia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GNB','Guinea-Bissau','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GNQ','Equatorial Guinea','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GRC','Greece','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GTM','Guatemala','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GUY','Guyana','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HND','Honduras','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HRV','Croatia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HTI','Haiti','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HUN','Hungary','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IDN','Indonesia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IRL','Ireland','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('IRQ','Iraq','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ISL','Iceland','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ISR','Israel','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ITA','Italy','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KAZ','Kazakstan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KEN','Kenya','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KGZ','Kyrgyzstan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KIR','Kiribati','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('KOR','South Korea','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LAO','Laos','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LBN','Lebanon','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LBR','Liberia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LKA','Sri Lanka','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LTU','Lithuania','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LVA','Latvia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MDA','Moldova','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MDV','Maldives','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MHL','Marshall Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MKD','Macedonia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MLI','Mali','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MLT','Malta','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MMR','Myanmar','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MNG','Mongolia','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MOZ','Mozambique','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MRT','Mauritania','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MUS','Mauritius','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MWI','Malawi','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NAM','Namibia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NER','Niger','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NIC','Nicaragua','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NRU','Nauru','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PAK','Pakistan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PAN','Panama','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PER','Peru','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PHL','Philippines','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PLW','Palau','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('POL','Poland','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PRT','Portugal','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PRY','Paraguay','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ROM','Romania','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('RWA','Rwanda','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SEN','Senegal','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SGP','Singapore','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SLE','Sierra Leone','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SLV','El Salvador','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SMR','San Marino','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SOM','Somalia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('STP','Sao Tome and Principe','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SUR','Suriname','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SVK','Slovakia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SVN','Slovenia','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SYC','Seychelles','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SYR','Syria','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TCD','Chad','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TGO','Togo','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TJK','Tajikistan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TKM','Turkmenistan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TTO','Trinidad and Tobago','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TUN','Tunisia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TUR','Turkey','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TWN','Taiwan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('TZA','Tanzania','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('UGA','Uganda','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('UKR','Ukraine','Europe');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('URY','Uruguay','South America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('UZB','Uzbekistan','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VUT','Vanuatu','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('YEM','Yemen','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ZAF','South Africa','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ZMB','Zambia','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ZWE','Zimbabwe','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CUB','Cuba','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('PRK','North Korea','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VNM','Vietnam','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('LBY','Libyan Arab Jamahiriya','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HKG','Hong Kong','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MAC','Macao','Asia');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('MYT','Mayotte','Africa');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('SPM','Saint Pierre and Miquelon','North America');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CCK','Cocos (Keeling) Islands','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('CXR','Christmas Island','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('HMD','Heard Island and McDonald Islands','Antarctica');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('NFK','Norfolk Island','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('ASM','American Samoa','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('GUM','Guam','Oceania');
INSERT INTO `forum_i`.`pais` (`code`, `name`, `continent`) VALUES ('VIR','Virgin Islands, U.S.','North America');


INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('185','Pakistani National Assembly','2018-07-25','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('173','President','2018-07-29','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('173','President','2018-07-29','Second Round if needed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('17','Cambodian National Assembly','2018-07-29','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('224','Zimbabwean National Assembly','2018-07-30','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('224','Zimbabwean Senate','2018-07-30','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('224','President','2018-07-30','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('121','Referendum','2018-07-30','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('194','Rwandan Chamber of Deputies','2018-09-02','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('31','Swedish Parliament','2018-09-09','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('71','Referendum','2018-09-23','Tentative');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('79','Swazi House of Assembly','2018-09-30','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('60','Brazilian Chamber of Deputies','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('59','Bosnia and Herzegovina House of Representatives','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('59','President','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('59','Bosnia and Herzegovina House of Peoples','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('168','Latvian Parliament','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('60','President','2018-10-07','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('22','Luxembourg Chamber of Deputies','2018-10-14','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('73','Afgahni House of People','2018-10-20','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('60','President','2018-10-28','Second Round if needed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('117','President','2018-10-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('153','President','2018-10-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('139','President','2018-10-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('172','Referendum','2018-10-31','Tentative');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('85','Referendum','2018-11-04','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('68','US House of Representatives','2018-11-06','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('238','Non-Voting Delegate to US House of Representatives','2018-11-06','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('68','US Senate','2018-11-06','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('238','Legislature of Guam','2018-11-06','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('143','Bissau-Guinean Peoples National Assembly','2018-11-18','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('64','Malagasy National Assembly','2018-11-24','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('64','President','2018-11-24','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('71','Referendum','2018-11-25','Tentative');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('228','Libyan Council of Deputies ','2018-12-10','Tentative');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('228','President','2018-12-10','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('118','Congolese National Assembly','2018-12-23','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('118','President','2018-12-23','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('64','President','2018-12-24','Second Round if needed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('208','Togolese National Assembly','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('141','Guinean National Assembly','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('197','Sierra Leonean Parliament','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('144','Equatorial Guinean House of Peoples Representatives','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('178','Mauritanian National Assembly','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('173','Malian National Assembly','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('144','Equatorial Guinean Senate','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('170','President','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('117','Cameroonian National Assembly','2018-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('109','Bangladeshi National Parliament','2019-01-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('198','President','2019-02-03','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('66','President','2019-02-16','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('66','Nigerian Senate','2019-02-16','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('66','Nigerian House of Representatives','2019-02-16','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('195','President','2019-02-28','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('133','Estonian Parliament','2019-03-03','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('198','President','2019-03-10','Second Round if needed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('217','President','2019-03-31','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('152','President','2019-04-17','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('152','Indonesian House of Representatives','2019-04-17','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('186','President','2019-05-05','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('180','Malawian National Assembly','2019-05-21','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('180','President','2019-05-21','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('29','Referendum','2019-06-15','Confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('149','Croatian Assembly','2019-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('46','Cook Islands Parliament','2019-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('156','Israeli Knesset','2019-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('147','Guyanese National Assembly','2020-05-30','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('209','President','2020-11-06','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('75','Sudanese National Assembly','2020-12-31','Date not confirmed');
INSERT INTO `forum_i`.`eleccion` (`pais_id`, `nombre` ,`fecha`,  `estado`) VALUES ('191','President','2021-01-31','Tentative');



#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('1', 'Arts');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('2', 'Entertainment');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('3', 'Politics');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('4', 'Business');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('5', 'Entrepreneur');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('6', 'Investments');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('7', 'Financial Education');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('8', 'Personal Growth');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('9', 'Philosophy');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('10','Society');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('11','Books & Knowledge');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('12','Life');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('13','Innovations & Tech');
#INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('14','Sciences');

INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('1', 'Politics');
# noticias de prensa, noticias de politicos, noticias de autoridades, leyes nacionales y locales, intelectuales, líderes, estadísticas, sociedad digital
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('2', 'Economy and Business');
#negocio, emprendimiento, innovación, educación financiera
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('3', 'Personal Growth');
# hábitos, cómo ganar dinero, cómo ser uno mismo
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('4', 'Financial Freedom');
# libros, cursos, videos, audios
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('5', 'Leiusure');
# deporte y entretenimiento
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('6', 'Science');
# ciencia de la información, ingeniería, tecnología ...
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('7', 'Ethic');
# aborto, matrimonio, valores, honestidad, respeto a los demás
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('8', 'Society');
# problema sociales y de la comunidad, del vecindario, de la ciudad, de la región o del pais, trabajo en empresa, relaciones laborales, inmigración, marihuana
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('9', 'Art');
# pintura, arquitectura, diseño
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('10','Religion');
# cristianismo, sincretismo, budismo, islamismo
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('11','Economic system');
# socialismo, capitalismo, libre mercado, proteccionismo, libertad, colectivismo, derecho de propiedad, estadísticas
INSERT INTO `forum_i`.`theme` (`id`, `name`) VALUES ('12','Knowledge');
# libros, revistas, tesis

# Según el estudio: los tópicos más importantes son la inmigración .valores, diferentes puntos de vista politico: identidad de género, desigualdad, feminismo.

#Calificar tags o topicos según importancia y posiblemente al desplegar los tags se ordenen por importancia o por tendencia actual.

INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('1','Art');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('2','Comics');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('3','Culture');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('4','Film');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('5','Food');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('6','Gaming');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('7','Humor');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('8','Lit');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('9','Music');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('10','Photography');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('11','Social media');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('12','Sports');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('13','True crime');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('14','Writing');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('15','Industry');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('16','Business');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('17','Economy');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('18','Entrepreneurship');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('19','Freelancing');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('20','Leadership');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('21','Productivity');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('22','Work');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('23','Innovation ');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('24','Tech');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('25','Artificial intelligence');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('26','Cryptocurrency');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('27','Cybersecurity');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('28','Data science');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('29','Digital design');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('30','Javascript');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('31','Math');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('32','Neuroscience');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('33','Programming');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('34','Science');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('35','Self-driving cars');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('36','Software engineering');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('37','Space');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('38','Technology');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('39','Life');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('40','Family');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('41','Health');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('42','Mental health');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('43','Parenting');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('44','Personal finance');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('45','Pets');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('46','Psychedelics');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('47','Psychology');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('48','Relationships');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('49','Self');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('50','Sexuality');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('51','Spirituality');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('52','Travel');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('53','Wellness');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('54','Society');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('55','Basic income');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('56','Cities');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('57','Education');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('58','Environment');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('59','Equality');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('60','Future');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('61','Gun control');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('62','History');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('63','LGBTQIA');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('64','Media');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('65','Philosophy');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('66','Politics');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('67','Race');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('68','San Francisco');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('69','Transportation');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('70','Women');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('71','World');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('72','Marketing');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('73','Creativity');
INSERT INTO `forum_i`.`topic` (`id`, `name`) VALUES ('74','Drugs');

#Tag del emprendedor
#INSERT INTO `forum_i`.`etiqueta` (`id`, `name`) VALUES ('1','Problema');
#INSERT INTO `forum_i`.`etiqueta` (`id`, `name`) VALUES ('2','Solución');
#INSERT INTO `forum_i`.`etiqueta` (`id`, `name`) VALUES ('3','Objetivo');

commit
